version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: superset-lite-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superset_lite_metadata
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: superset-lite-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cachedata:/data

volumes:
  pgdata:
  cachedata:
